# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            CS373 Summer 2015
tagline:          'by Kahli Holmes'
description:      'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://lanyon.getpoole.com

author:
  name:           'Kahli Holmes'
  url:            kahlih.github.io/

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/kahlih/kahlih.github.io
